definitions:
  checkstatus.Attribute:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  checkstatus.CardAuthInfo:
    properties:
      authorizationResponseId:
        type: string
      cardholderName:
        type: string
      expiration:
        type: string
      pan:
        type: string
    type: object
  checkstatus.MerchantOrderParam:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  checkstatus.OrderStatusRequest:
    properties:
      orderId:
        description: Order id the same as order number
        type: string
      password:
        description: bank merchant passowrd
        type: string
      userName:
        description: bank merchant user name
        type: string
    required:
    - orderId
    type: object
  checkstatus.OrderStatusResponse:
    properties:
      actionCode:
        type: integer
      actionCodeDescription:
        type: string
      amount:
        type: number
      attributes:
        items:
          $ref: '#/definitions/checkstatus.Attribute'
        type: array
      cardAuthInfo:
        $ref: '#/definitions/checkstatus.CardAuthInfo'
      currency:
        type: string
      date:
        type: integer
      errorCode:
        type: string
      errorMessage:
        type: string
      fraudLevel:
        type: integer
      ip:
        type: string
      merchantOrderParams:
        items:
          $ref: '#/definitions/checkstatus.MerchantOrderParam'
        type: array
      orderDescription:
        type: string
      orderNumber:
        type: string
      orderStatus:
        type: integer
    type: object
  confirpayment.ConfirmPaymentRequest:
    properties:
      MDORDER:
        description: md order which was created on order registration
        type: string
      passwordEdit:
        description: otp password that comes to phone number
        type: string
      request_id:
        description: Request id comes from previouse request of card submission
        type: string
    required:
    - MDORDER
    - passwordEdit
    type: object
  constants.HttpError:
    properties:
      error:
        type: string
    type: object
  constants.ResponseWithMessage:
    properties:
      message:
        type: string
    type: object
  orderregistration.OrderRegistrationRequest:
    properties:
      amount:
        description: Order amount in the minor denomination (for example, cents).
        type: integer
      api_client:
        description: Api client please specify this this should be either "halkbank"
          or "senagat"
        type: string
      currency:
        description: Payment currency code in the ISO 4217 format
        maxLength: 3
        minLength: 3
        type: string
      description:
        description: Free form description of the order.
        maxLength: 512
        type: string
      language:
        description: "Optional fields\n\n\t\tLanguage code in the ISO 639-1 format.\n\t\tIf
          unspecified, SmartVista E-commerce Payment Gateway uses\n\t\tthe default
          language from the merchant settings.\n\n\t\tError messages are returned
          in this language."
        maxLength: 2
        minLength: 2
        type: string
      orderNumber:
        description: "Number (identifier) of the order in the merchant’s online store
          system.\n\t\tIt is unique for every store in the system and is generated
          on the order registration."
        maxLength: 32
        minLength: 1
        type: string
      password:
        description: bank merchant password
        type: string
      returnUrl:
        type: string
      sessionTimeoutSecs:
        description: "The order lifespan duration can be taken from the following
          parameters (from the highest priority to the lowest):\n\t\t· sessionTimeoutSecs
          transferred in a request. It overrides all other order timeout settings.\n\t\t·
          If the sessionTimeoutSecs parameter is not specified, the value from the
          merchant’s settings is used.\n\t\tIt is configured by the Alternative session
          timeout option that must be enabled and\n\t\tthe Session duration additional
          parameter that must be specified.\n\t\t· If none of the above mentioned
          settings is specified\n\t\t(neither sessionTimeoutSecs nor merchant’s timeout),\n\t\tthe
          default value set in Administration > System settings by the default.session.timeout.milliseconds\n\t\tsystem
          setting is used (the default value is 1200 seconds) .\n\t\tIf the request
          contains the expirationDate parameter, the sessionTimeoutSecs parameter
          is ignored."
        type: integer
      userName:
        description: bank merchant user name
        type: string
    required:
    - amount
    - api_client
    - description
    - password
    - userName
    type: object
  orderregistration.OrderRegistrationResponse:
    properties:
      errorMessage:
        description: Error message (in requested language, empty on success)
        type: string
      formUrl:
        description: URL of the payment page (absent on error)
        type: string
      orderId:
        description: Unique order ID generated by EPG (absent on error)
        type: string
      recurrenceId:
        description: Identifier for recurring payments (only for recurring payments)
        type: string
    type: object
  submitcard.SubmitCardRequest:
    properties:
      $CVC:
        description: CVC is secure code on back side of your card
        type: string
      $EXPIRY:
        description: should be in form like YYYYMM example 202709
        type: string
      $PAN:
        description: PAN is a number on card 12 digit code
        type: string
      MDORDER:
        description: Another meaning of order_id
        type: string
      TEXT:
        description: Text is card holder name and surname
        type: string
      language:
        description: language is language
        type: string
    required:
    - $CVC
    - $EXPIRY
    - $PAN
    - MDORDER
    - TEXT
    - language
    type: object
info:
  contact: {}
paths:
  /check-status:
    post:
      consumes:
      - application/json
      description: Check's order status from bank.
      parameters:
      - description: check order status request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/checkstatus.OrderStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully checked status
          schema:
            $ref: '#/definitions/checkstatus.OrderStatusResponse'
        "400":
          description: Invalid request body or parameters
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Check order status. Make this request finally
      tags:
      - epg
  /confirm-payment:
    post:
      consumes:
      - application/json
      description: Confirm Payment by writing otp code.
      parameters:
      - description: Payment Confirmation request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/confirpayment.ConfirmPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Just message that says it was succesfully
          schema:
            $ref: '#/definitions/constants.ResponseWithMessage'
        "500":
          description: Some Confirmation Error
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Confirm Payment Make This Request Third
      tags:
      - epg
  /register-order:
    post:
      consumes:
      - application/json
      description: Register an order for payment processing.
      parameters:
      - description: Order Registration Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/orderregistration.OrderRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful order registration
          schema:
            $ref: '#/definitions/orderregistration.OrderRegistrationResponse'
        "400":
          description: Invalid request body or parameters
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Order Registration Make this Request First
      tags:
      - epg
  /submit-card:
    post:
      consumes:
      - application/json
      description: Submit card data to move next into step.
      parameters:
      - description: Card submission request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/submitcard.SubmitCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Just message that says it was succesfully
          schema:
            $ref: '#/definitions/constants.ResponseWithMessage'
        "400":
          description: Submit card to bank error
          schema:
            $ref: '#/definitions/constants.HttpError'
        "500":
          description: Get otp error
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Card Submission Make This Request Second
      tags:
      - epg
swagger: "2.0"
