definitions:
  checkversion.CheckVersionRequest:
    properties:
      base_url:
        description: bank url < epg_server_IP_address>
        type: string
    type: object
  checkversion.EPGVersionsResponse:
    properties:
      error1:
        type: string
      error2:
        type: string
      version1:
        type: string
      version2:
        type: string
    type: object
  constants.HttpError:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /check-version:
    post:
      consumes:
      - application/json
      description: This API endpoint checks the versions of E-commerce Payment Gateway
        data for two URLs constructed from a provided base URL.
      parameters:
      - description: Request containing the base URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/checkversion.CheckVersionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success response containing versions for both URLs
          schema:
            $ref: '#/definitions/checkversion.EPGVersionsResponse'
        "400":
          description: on invalid request body
          schema:
            $ref: '#/definitions/constants.HttpError'
        "500":
          description: on check version function error
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Check EPG Versions
      tags:
      - epg
swagger: "2.0"
