definitions:
  confirpayment.ConfirmPaymentRequest:
    properties:
      MDORDER:
        description: md order which was created on order registration
        type: string
      passwordEdit:
        description: otp password that comes to phone number
        type: string
      request_id:
        description: Request id comes from previouse request of card submission
        type: string
    type: object
  constants.HttpError:
    properties:
      error:
        type: string
    type: object
  orderregistration.OrderRegistrationRequest:
    properties:
      amount:
        description: Order amount in the minor denomination (for example, cents).
        type: integer
      currency:
        description: Payment currency code in the ISO 4217 format
        maxLength: 3
        minLength: 3
        type: string
      description:
        description: Free form description of the order.
        maxLength: 512
        type: string
      language:
        description: "Optional fields\n\n\t\tLanguage code in the ISO 639-1 format.\n\t\tIf
          unspecified, SmartVista E-commerce Payment Gateway uses\n\t\tthe default
          language from the merchant settings.\n\n\t\tError messages are returned
          in this language."
        maxLength: 2
        minLength: 2
        type: string
      orderNumber:
        description: "Order details\n\n\t\tNumber (identifier) of the order in the
          merchant’s online store system.\n\t\tIt is unique for every store in the
          system and is generated on the order registration."
        maxLength: 32
        minLength: 1
        type: string
      password:
        description: User’s password.
        maxLength: 30
        minLength: 1
        type: string
      returnUrl:
        description: URL to which the customer is redirected after a successful payment.
        maxLength: 512
        minLength: 1
        type: string
      sessionTimeoutSecs:
        description: "The order lifespan duration can be taken from the following
          parameters (from the highest priority to the lowest):\n\t\t· sessionTimeoutSecs
          transferred in a request. It overrides all other order timeout settings.\n\t\t·
          If the sessionTimeoutSecs parameter is not specified, the value from the
          merchant’s settings is used.\n\t\tIt is configured by the Alternative session
          timeout option that must be enabled and\n\t\tthe Session duration additional
          parameter that must be specified.\n\t\t· If none of the above mentioned
          settings is specified\n\t\t(neither sessionTimeoutSecs nor merchant’s timeout),\n\t\tthe
          default value set in Administration > System settings by the default.session.timeout.milliseconds\n\t\tsystem
          setting is used (the default value is 1200 seconds) .\n\t\tIf the request
          contains the expirationDate parameter, the sessionTimeoutSecs parameter
          is ignored."
        type: integer
      userName:
        description: |-
          User credentials
          Login of the API user on whose behalf requests are processed for a particular merchant.
        maxLength: 30
        minLength: 1
        type: string
    required:
    - amount
    - currency
    - password
    - returnUrl
    - userName
    type: object
  orderregistration.OrderRegistrationResponse:
    properties:
      errorCode:
        description: Response code
        type: integer
      errorMessage:
        description: Error message (in requested language, empty on success)
        type: string
      formUrl:
        description: URL of the payment page (absent on error)
        type: string
      orderId:
        description: Unique order ID generated by EPG (absent on error)
        type: string
      recurrenceId:
        description: Identifier for recurring payments (only for recurring payments)
        type: string
    type: object
  submitcard.RequestIdResponse:
    properties:
      request_id:
        type: string
    type: object
  submitcard.SubmitCardRequest:
    properties:
      $CVC:
        type: string
      $EXPIRY:
        type: string
      $PAN:
        type: string
      MDORDER:
        type: string
      MM:
        type: string
      TEXT:
        type: string
      YYYY:
        type: string
      language:
        type: string
    type: object
info:
  contact: {}
paths:
  /confirm-payment:
    post:
      consumes:
      - application/json
      description: Confirm Payment by writing otp code.
      parameters:
      - description: Payment Confirmation request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/confirpayment.ConfirmPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: A string of success payment
          schema:
            type: string
        "500":
          description: Some Confirmation Error
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Confirm Payment
      tags:
      - epg
  /register-order:
    post:
      consumes:
      - application/json
      description: Register an order for payment processing.
      parameters:
      - description: Order Registration Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/orderregistration.OrderRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful order registration
          schema:
            $ref: '#/definitions/orderregistration.OrderRegistrationResponse'
        "400":
          description: Invalid request body or parameters
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Order Registration
      tags:
      - epg
  /submit-card:
    post:
      consumes:
      - application/json
      description: Submit card data to move next into step.
      parameters:
      - description: Card submission request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/submitcard.SubmitCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Coming request id of otp to use in next request confirmPayment
          schema:
            $ref: '#/definitions/submitcard.RequestIdResponse'
        "400":
          description: Submit card to bank error
          schema:
            $ref: '#/definitions/constants.HttpError'
        "500":
          description: Get otp error
          schema:
            $ref: '#/definitions/constants.HttpError'
      summary: Card Submission
      tags:
      - epg
swagger: "2.0"
